# Generated by Django 2.0.5 on 2018-05-10 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secretsmodules', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PurchasedItems',
            new_name='PurchasedItem',
        ),
    ]
