# Generated by Django 2.0.5 on 2018-05-10 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('secretsmodules', '0002_auto_20180510_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseditem',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secretsmodules.Cart'),
        ),
    ]
